[project]
name = "python-huey-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anyio>=4.9.0",
    "huey>=2.5.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
